/**
 * Domain vocabulary of the cognitive pipeline: SAR experiences, predictions,
 * temp strategies, calibration buckets, clusters, and the taxonomy snapshot.
 * Plain value types — every object crossing the JSONL store boundary is a
 * plain, JSON-serializable record.
 * @module @deepseek-ai/dsh-cognitive-pipeline/types
 */

/** Quantified short/medium-term feedback of one experience (0–10 each). */
export interface OutcomeUtility {
  /** Material or monetary gain/loss (5 = neutral). */
  readonly materialGain: number
  /** Emotional valence (5 = neutral). */
  readonly emotionalValence: number
  /** Energy / cognitive cost spent (5 = moderate). */
  readonly energyCost: number
}

/** The retrieval channels fused by the hot loop, mirroring the parallel
 * recall channels of human memory (类比/情境/症状/因果). */
export type ChannelKey = 'semantic' | 'situational' | 'symptom' | 'outcome'

/** Per-channel fusion weights, learned from feedback error (default 1 each). */
export interface ChannelWeights {
  /** Action-text similarity (the classic cosine axis). */
  readonly semantic: number
  /** Situation-structure similarity (premise differentiation lives here). */
  readonly situational: number
  /** Failure-signature substring overlap. */
  readonly symptom: number
  /** Outcome-polarity priority when the query itself carries failure markers. */
  readonly outcome: number
}

/** The Situation–Action–Result triplet a raw experience is encoded into. */
export interface SarTriplet {
  /** Objective situation constraints, without subjective emotion. */
  readonly situation: string
  /** The concrete behavior strategy the actor took. */
  readonly action: string
  /** Observable short+long term feedback, with quantified gain/cost. */
  readonly outcome: string
  /** Action verb keywords used by the lightweight action vectorizer. */
  readonly actionKeywords: readonly string[]
  /** Quantified utility of the outcome, the clustering axis. */
  readonly outcomeUtility: OutcomeUtility
}

/** Verification state of one experience, gate for cold-loop clustering eligibility. */
export type ExperienceVerification = 'unverified' | 'provisional' | 'verified'

/** One stored experience (the main memory row). */
export interface Experience {
  readonly expId: string
  readonly sar: SarTriplet
  /** Deterministic hashed action vector (the retrieval axis). */
  readonly actionVector: readonly number[]
  /** Deterministic hashed outcome vector (the clustering axis). */
  readonly outcomeVector: readonly number[]
  /** Real-embedding vector of the action text (roadmap R3), present only
   * when the embedding seam was enabled at write time. The semantic
   * retrieval channel prefers it over the hashed action vector; experiences
   * without one keep the hash fallback. */
  readonly embedding?: readonly number[]
  /** Current cluster assignment, null until the first cold-loop rebuild. */
  readonly clusterId: number | null
  /** Human strategy label of the assigned cluster. */
  readonly strategyLabel: string | null
  /** Epoch milliseconds at creation. */
  readonly timestamp: number
  /** Last observed absolute prediction error (0–1), null before any feedback. */
  readonly predictionError: number | null
  /** Rolling sum of absolute prediction errors (the rebuild trigger). */
  readonly cumulativeError: number
  /** Times this experience's cluster matched a hot-loop prediction. */
  readonly hitCount: number
  /** Times the predicted outcome matched the actual outcome. */
  readonly positiveCount: number
  /** True when this experience was generated by the LLM route as a
   * retrieval-only candidate awaiting real verification, never a first-hand
   * record. Ordinary `remember_experience` writes are false. */
  readonly simulated: boolean
  /** Clustering-eligibility gate: only `verified` experiences shape clusters;
   * `provisional` may be rolled back by contradictory feedback, and
   * `unverified` simulated samples never cluster. Ordinary experiences are
   * `verified` from birth. */
  readonly verification: ExperienceVerification
  /** Cumulative evidence score from real feedback; meaningful only for
   * simulated experiences (ordinary ones are verified by construction). */
  readonly evidenceScore: number
  /** True when this experience is a pipeline-own observation (e.g. a recorded
   * retrieval-routing failure) rather than a user-task experience. Meta
   * experiences with a non-neutral utility join the cold-loop sample so the
   * pipeline can learn about its own failure modes. Absent on legacy rows. */
  readonly meta?: boolean
}

/** One logged hot-loop prediction (the prediction log row). */
export interface Prediction {
  readonly predictionId: string
  /** Optional experience this prediction is bound to via feedback. */
  readonly expId: string | null
  readonly situation: string
  readonly action: string
  readonly predictedOutcome: string
  /** Model-raw probability before shrinkage (0–1). */
  readonly rawProbability: number
  /** Calibrated probability after shrinkage and bucket correction (0–1). */
  readonly calibratedProbability: number
  /** Lower bound of the 80% confidence interval (0–1). */
  readonly confidenceLow: number
  /** Upper bound of the 80% confidence interval (0–1). */
  readonly confidenceHigh: number
  readonly isNovel: boolean
  readonly usedTempStrategy: boolean
  readonly clusterId: number | null
  /** Signature hash of the exploration scratchpad this prediction reused
   * (`usedTempStrategy`), so feedback can fold the real-world prediction error
   * back into the exploration entry's ROI ledger. Null for predictions that
   * did not reuse a scratchpad. */
  readonly exploredActionHash: string | null
  /** Epoch milliseconds at prediction. */
  readonly timestamp: number
  /** Actual outcome text once reported via feedback, null otherwise. */
  readonly actualOutcome: string | null
  /** Absolute prediction error after feedback (0–1), null before resolution. */
  readonly predictionError: number | null
  /** Epoch milliseconds at feedback, null before resolution. */
  readonly resolvedAt: number | null
  /** Per-channel contributions (w_c · s_c) of the fused top-1 hit at predict
   * time, in [semantic, situational, symptom, outcome] order. The feedback
   * loop uses the dominant channel for error-driven weight learning; absent
   * for novel predictions with no bound hit. */
  readonly fusion: {
    readonly scores: readonly number[]
  } | null
}

/** Lifecycle state of one scratchpad strategy. */
export type TempStrategyStatus = 'active' | 'graduated' | 'expired'

/** One OOD scratchpad row: a tentative strategy awaiting enough hits to graduate. */
export interface TempStrategy {
  readonly signatureHash: string
  /** The trial action text the strategy encodes. */
  readonly trialAction: string
  /** Result placeholder awaiting the first feedback. */
  readonly pendingResult: string | null
  /** Times this strategy was matched and reused by the hot loop. */
  readonly hitCount: number
  /** Times a matched reuse ended positively. */
  readonly positiveCount: number
  /** Epoch milliseconds at creation. */
  readonly createdAt: number
  /** Epoch milliseconds after which the strategy is no longer suggested. */
  readonly expiresAt: number
  readonly status: TempStrategyStatus
  /** Optional experience that seeded this strategy. */
  readonly sourceExpId: string | null
}

/** One active-exploration attempt (scheme 2): a scratchpad created within the
 * curiosity budget. ROI is tracked from the strategy's terminal state, then
 * validated by the strategy's real-world reuse: when a later prediction reuses
 * the scratchpad and receives feedback, the prediction error folds back here
 * (EWMA), so "did this exploration actually reduce |calibrated − observed|"
 * is measured on the same ruler as every other prediction. */
export interface ExploreEntry {
  /** Epoch milliseconds at creation. */
  readonly ts: number
  /** The trial action that was explored. */
  readonly action: string
  /** The scratchpad signature hash this entry tracks. */
  readonly scratchpadHash: string
  /** Whether the action passed the reversibility safety gate. */
  readonly reversible: boolean
  /** Terminal outcome: 'graduated' | 'expired' | null while active. */
  readonly outcome: 'graduated' | 'expired' | null
  /** EWMA of the prediction errors from real-world reuse of this entry's
   * scratchpad, null until the first feedback on a reused prediction. */
  readonly validatedError: number | null
  /** Whether the exploration paid off in practice: the reused predictions'
   * EWMA error stayed below {@link exploreValidationErrorThreshold} (true),
   * crossed it (false), or no reuse feedback exists yet (null). */
  readonly validated: boolean | null
}

/** Persisted active-exploration state (one per pipeline store). */
export interface ExplorationState {
  /** Local date key (`YYYY-MM-DD`) of the current budget window. */
  readonly date: string
  /** How many entries the window has consumed. */
  readonly used: number
  /** Every exploration attempt, newest last. */
  readonly entries: readonly ExploreEntry[]
}

/** Lifecycle of one autonomous exploration task (scheme 2 execution). */
export type ExplorationTaskStatus = 'pending' | 'running' | 'completed' | 'failed'

/** One queued autonomous exploration: a cross-session goal a background
 * agent session picks up, executes silently, and writes back as experience. */
export interface ExplorationTask {
  readonly taskId: string
  /** The exploration goal the executing session is told to pursue. */
  readonly goal: string
  readonly status: ExplorationTaskStatus
  /** Epoch milliseconds at creation. */
  readonly createdAt: number
  /** Epoch milliseconds when a scheduler session picked it up, null while pending. */
  readonly pickedUpAt: number | null
  /** The executing session's outcome, null until settled. */
  readonly result: string | null
}

/** Lifetime calibration statistics for one confidence decile. */
export interface CalibrationBucket {
  /** Decile index 0–9 covering [bucketIndex*10, (bucketIndex+1)*10) percent. */
  readonly bucketIndex: number
  readonly totalCount: number
  readonly hitCount: number
  /** hitCount / totalCount; null before any count. */
  readonly empiricalAccuracy: number | null
}

/** Expected utility interval for one cluster. */
export interface UtilityRange {
  readonly low: number
  readonly high: number
}

/** One cold-loop cluster: a named strategy family with grounded evidence. */
export interface Cluster {
  readonly clusterId: number
  /** Naming format: "当【触发条件】出现，应【行动姿态】，预期获得【效用区间】". */
  readonly name: string
  /** Decision rule "if condition X then action Y". */
  readonly decisionRule: string
  readonly expectedUtilityRange: UtilityRange
  /** At least three distinct experience ids grounding this cluster. */
  readonly supportingEvidenceIds: readonly string[]
  /** Fallback strategy when match confidence < 60%. */
  readonly fallbackAction: string
  /** Epoch milliseconds at creation. */
  readonly createdAt: number
  readonly origin: 'cold-loop' | 'temp-graduation'
  readonly sampleCount: number
  /** Rolling sum of prediction errors of member experiences. */
  readonly cumPredictionError: number
  /** Whether this cluster is a proven success pattern or a risk pattern. */
  readonly polarity: 'success' | 'risk'
  /** Normalized centroid of member situation vectors (the reference axis). */
  readonly situationCentroid: readonly number[]
}

/** One decision rule rendered into the dynamic system-prompt summary. */
export interface TaxonomyRule {
  readonly condition: string
  readonly action: string
  readonly utilityRange: UtilityRange
  /** Whether the rule recommends a proven action or a risk-avoidance stance. */
  readonly polarity: 'success' | 'risk'
}

/** A matched success cluster returned as a strategy reference. */
export interface SuccessReference {
  readonly clusterId: number
  readonly clusterName: string
  readonly decisionRule: string
  readonly utilityRange: UtilityRange
}

/** The taxonomy consulted during one retrieval: which strategy region the query
 * falls in, how confidently it was routed, and whether SAR has coverage there. */
export interface TaxonomyContext {
  /** Matched cluster (any polarity) whose situation centroid clears the coverage threshold. */
  readonly cluster: {
    readonly clusterId: number
    readonly name: string
    readonly decisionRule: string
    readonly polarity: 'success' | 'risk'
  } | null
  /** Situation-centroid cosine to the matched cluster (0 when none matched). */
  readonly similarity: number
  /** Best-minus-second-best cluster cosine; small margins mean unreliable routing. */
  readonly margin: number
  /** Whether the query situation falls inside the taxonomy's covered region. */
  readonly coverage: 'covered' | 'gap' | 'no-taxonomy'
}

/** One completed agent turn reconstructed from the session log, as the candidate
 * raw material for automatic experience accumulation. */
export interface TurnEpisode {
  /** Situation material: the user request text(s) of the turn. */
  readonly situation: string
  /** Action material: the tool calls and assistant text of the turn. */
  readonly action: string
  /** Outcome material: the turn end reason and any error/final text. */
  readonly outcome: string
  /** How many tool calls the turn made (the deterministic cost pre-filter uses it). */
  readonly toolCallCount: number
  /** Whether any tool result in the turn failed. */
  readonly failed: boolean
  /** The turn sequence number. */
  readonly turnId: number
}

/** The LLM route's accumulation judgment for one episode. */
export interface AccumulationDecision {
  /** Whether the episode is worth accumulating as a new experience. */
  readonly shouldAccumulate: boolean
  /** The SAR triplet to write when accumulating; absent when rejected. */
  readonly sar: {
    readonly situation: string
    readonly action: string
    readonly outcome: string
    readonly utility: OutcomeUtility
  } | null
}

/** The LLM route's reference-derivation judgment for one anchor set. */
export interface DeriveReferenceDecision {
  /** Whether the similar history yields a common pattern worth generalizing. */
  readonly shouldDerive: boolean
  /** The reference SAR extracted from the commonalities; absent when rejected. */
  readonly sar: {
    readonly situation: string
    readonly action: string
    readonly outcome: string
    readonly utility: OutcomeUtility
  } | null
}

/** The LLM route's retrieval-refinement judgment (template 7): does the fused
 * top hit genuinely apply to the current situation/action? */
export interface RefineRetrievalDecision {
  /** Whether the top candidate experience genuinely applies. */
  readonly shouldKeep: boolean
  /** The expId the LLM judged inapplicable when rejecting. */
  readonly rejectedExpId: string | null
  /** One-line reason, surfaced in the advice for observability. */
  readonly reason: string | null
}

/** The compressed cognitive-framework summary injected into the hot loop. */
export interface TaxonomyState {
  readonly version: number
  /** One-sentence summary of the current taxonomy (≤30 chars, zh). */
  readonly summaryShort: string
  /** Top decision rules, rendered in order. */
  readonly rules: readonly TaxonomyRule[]
  /** Epoch milliseconds of the last accepted rebuild. */
  readonly updatedAt: number
}

/** Outcome of one hot-loop predict call (the `/infer` contract). */
export interface PredictResult {
  readonly predictionId: string
  readonly advice: string
  readonly rawProbability: number
  readonly calibratedProbability: number
  readonly confidenceLow: number
  readonly confidenceHigh: number
  readonly isNovel: boolean
  /** Which OOD math signal fired, or 'none'. */
  readonly oodSignal: 'none' | 'low-similarity' | 'flat-top' | 'high-strangeness'
  /** Matched history sample count feeding the calibration prior. */
  readonly topHitCount: number
  readonly usedTempStrategy: boolean
  readonly clusterId: number | null
  /** Closest proven success cluster matched by the situation, or null. */
  readonly successReference: SuccessReference | null
  /** Taxonomy consulted during retrieval: routed region, confidence, coverage. */
  readonly taxonomyContext: TaxonomyContext
}

/** Outcome of one feedback call (the `/feedback` contract). */
export interface FeedbackResult {
  readonly status: 'logged'
  readonly predictionError: number
  readonly triggerRebuild: boolean
  readonly rebuildReason: string | null
}

/** One registered meta-cognition loop (a named special-experience layer). */
export interface MetaLoopSpec {
  /** Stable loop identity; its predictions carry a `loop:<name>` situation
   * prefix so the loop's decision history forms its own retrievable layer. */
  readonly name: string
  /** One-line description surfaced in inspection. */
  readonly description: string
}

/** Per-loop aggregation for inspection: the loop's decision history under
 * the same |calibrated − observed| ruler as every other prediction. */
export interface CognitiveLoopStats {
  readonly name: string
  readonly description: string
  readonly predictionCount: number
  readonly resolvedCount: number
  /** Mean |calibrated − observed| over resolved predictions, null when none. */
  readonly avgPredictionError: number | null
}

/** Outcome of one cold-loop rebuild (the `/rebuild/trigger` contract). */
export interface RebuildResult {
  readonly scope: 'local' | 'global'
  /** Whether the proposed taxonomy was accepted and written back. */
  readonly accepted: boolean
  /** True when the rebuild was postponed for insufficient labeled validation
   * samples rather than rejected on merit; the store is left untouched. */
  readonly deferred: boolean
  /** Validation-set error under the old taxonomy. */
  readonly oldError: number | null
  /** Validation-set error under the proposed taxonomy. */
  readonly newError: number | null
  /** (new - old) / old; null when the old error is zero. */
  readonly deltaError: number | null
  readonly clusterCount: number
  /** Clusters rejected by the evidence hard-constraint check. */
  readonly rejectedClusters: number
  readonly sampleCount: number
  /** Human-readable accept/reject/defer reason. */
  readonly reason: string
  readonly taxonomyVersion: number
}

/** Snapshot returned by the inspect tool / service. */
export interface InspectResult {
  readonly experienceCount: number
  readonly predictionCount: number
  readonly resolvedPredictionCount: number
  readonly clusterCount: number
  readonly activeTempStrategyCount: number
  readonly calibrationBuckets: readonly CalibrationBucket[]
  readonly taxonomy: TaxonomyState
  /** Learned multi-channel retrieval weights (feedback-driven). */
  readonly channelWeights: ChannelWeights
  /** Active-exploration statistics (scheme 2): budget, usage, ROI. */
  readonly exploration: {
    readonly budget: number
    readonly used: number
    readonly total: number
    readonly graduated: number
    readonly expired: number
    /** Explored strategies that paid off in practice (validated true). */
    readonly validated: number
    /** Explored strategies that failed in practice (validated false). */
    readonly refuted: number
    /** Average EWMA reuse error over validated/refuted entries, null when none. */
    readonly avgValidationError: number | null
    /** Autonomous task queue counts by status. */
    readonly tasks: { readonly pending: number; readonly running: number; readonly completed: number; readonly failed: number }
  }
  /** Registered meta-cognition loops and their per-loop calibration history. */
  readonly loops: readonly CognitiveLoopStats[]
  /** Recent resolved predictions, newest first. */
  readonly recentResolved: readonly Prediction[]
}

/** Raw experience text plus an optional explicit outcome for SAR extraction. */
export interface RememberInput {
  readonly rawText: string
}

/** One simulated-experience request: a hypothetical situation and proposed action. */
export interface SimulateInput {
  /** The hypothetical situation to reason about. */
  readonly situation: string
  /** The proposed action whose outcome is to be simulated. */
  readonly action: string
}

/** One hot-loop predict request. */
export interface PredictInput {
  readonly situation: string
  readonly action: string
  /** Optional context string folded into the calibration prompt. */
  readonly context?: string
}

/** One feedback request binding an actual outcome. */
export interface FeedbackInput {
  /** The prediction whose outcome is being reported. */
  readonly predictionId: string
  readonly actualOutcome: string
  /**
   * Actual outcome quality 0–10, required so every resolved prediction
   * carries a real, non-neutral utility signal; a neutral baseline is no
   * longer inferred from the outcome text.
   */
  readonly outcomeQuality: number
}
