#!/usr/bin/env bash
# install-frps.sh — one-shot frps (server) setup on a Linux box with a public IP.
# Downloads frp, writes /etc/frp/frps.toml with YOUR token, registers a systemd
# service (frps.service) and starts it. Run as root (or with sudo).
#
# Usage:
#   sudo ./install-frps.sh <strong-token> [remote-port] [version]
#     token      required — the same value goes into the Windows frpc config
#     remote-port  default 4080 (the public port phones will hit)
#     version    default v0.61.1
#
# After it runs, open ONLY these ports in the server firewall:
#   7000 (frp control channel) and <remote-port> (the tunnel).
# For HTTPS without warnings, add Caddy in front (see frp/README.md) and open
# only 443 instead.

set -euo pipefail

TOKEN="${1:?usage: install-frps.sh <strong-token> [remote-port] [version]}"
REMOTE_PORT="${2:-4080}"
VERSION="${3:-v0.61.1}"
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64) GOARCH="amd64" ;;
  aarch64|arm64) GOARCH="arm64" ;;
  *) echo "unsupported arch: $ARCH"; exit 1 ;;
esac

if [[ $EUID -ne 0 ]]; then
  echo "run as root: sudo $0 $*"
  exit 1
fi

FRP_DIR="/opt/frp"
WORK_DIR="$(mktemp -d)"
TARBALL="frp_${VERSION#v}_linux_${GOARCH}.tar.gz"
URL="https://github.com/fatedier/frp/releases/download/${VERSION}/${TARBALL}"

echo "==> downloading ${URL}"
wget -q "$URL" -O "${WORK_DIR}/${TARBALL}"
tar xzf "${WORK_DIR}/${TARBALL}" -C "$WORK_DIR"
mkdir -p "$FRP_DIR"
cp "${WORK_DIR}"/frp_${VERSION#v}_linux_${GOARCH}/frps "$FRP_DIR/frps"
chmod +x "$FRP_DIR/frps"

mkdir -p /etc/frp
cat > /etc/frp/frps.toml <<EOF
# frps server config — generated by install-frps.sh
bindPort = 7000
auth.token = "${TOKEN}"

# Optional: local-only dashboard (http://127.0.0.1:7500, admin/<dashboardPassword>)
# webServer.addr = "127.0.0.1"
# webServer.port = 7500
# webServer.user = "admin"
# webServer.password = "<dashboard-password>"
EOF

cat > /etc/systemd/system/frps.service <<EOF
[Unit]
Description=frp server (DSH Mobile gateway tunnel)
After=network.target

[Service]
Type=simple
ExecStart=${FRP_DIR}/frps -c /etc/frp/frps.toml
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now frps

echo ""
echo "==> frps installed and running (systemd: frps.service)"
echo "    control channel : 7000/tcp"
echo "    tunnel (phones) : ${REMOTE_PORT}/tcp  -> client's gateway :4080"
echo "    verify locally  : ss -ltnp | grep -E '7000|${REMOTE_PORT}'"
echo "    open in firewall: ufw allow 7000/tcp; ufw allow ${REMOTE_PORT}/tcp"
echo "    next            : run setup-frpc.ps1 on the Windows machine with the same token"
